### ISSUE TITLE
The elements are not connected to the relative Urls

### ISSUE THREAD

**Issue by paolospoto** [angelogulina/fua#3]
## Di che cosa si tratta?

Gli elementi della homepage non rispondono al relativo link

## Come lo riproduco?

Cliccare su un elemento

## Come dovrebbe funzionare?

Al click bisognerebbe navigare sulla pagina corrispondente al link

**Comment by angelogulina** [comment]
@paolospoto la PR: https://github.com/angelogulina/fuaa/pull/4 è chiusa. Chiudo questa!
